# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.sdot_nls <- function(u, v) {
    .Call('cccp_sdot_nls', PACKAGE = 'cccp', u, v)
}

.sdot_p <- function(u, v, m) {
    .Call('cccp_sdot_p', PACKAGE = 'cccp', u, v, m)
}

.snrm2_nls <- function(u) {
    .Call('cccp_snrm2_nls', PACKAGE = 'cccp', u)
}

.snrm2_p <- function(u, m) {
    .Call('cccp_snrm2_p', PACKAGE = 'cccp', u, m)
}

