# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.jdot <- function(us, vs) {
    .Call('cccp_jdot', PACKAGE = 'cccp', us, vs)
}

.jnrm2 <- function(us) {
    .Call('cccp_jnrm2', PACKAGE = 'cccp', us)
}

.ntsc_n <- function(ss, zs) {
    .Call('cccp_ntsc_n', PACKAGE = 'cccp', ss, zs)
}

.ntsc_l <- function(ss, zs) {
    .Call('cccp_ntsc_l', PACKAGE = 'cccp', ss, zs)
}

.ntsc_s <- function(ss, zs) {
    .Call('cccp_ntsc_s', PACKAGE = 'cccp', ss, zs)
}

.ntsc_p <- function(ss, zs, ms) {
    .Call('cccp_ntsc_p', PACKAGE = 'cccp', ss, zs, ms)
}

.ntsu_l <- function(Ws, ss, zs) {
    .Call('cccp_ntsu_l', PACKAGE = 'cccp', Ws, ss, zs)
}

.sdot_nls <- function(us, vs) {
    .Call('cccp_sdot_nls', PACKAGE = 'cccp', us, vs)
}

.sdot_p <- function(us, vs, ms) {
    .Call('cccp_sdot_p', PACKAGE = 'cccp', us, vs, ms)
}

.snrm2_nls <- function(us) {
    .Call('cccp_snrm2_nls', PACKAGE = 'cccp', us)
}

.snrm2_p <- function(us, ms) {
    .Call('cccp_snrm2_p', PACKAGE = 'cccp', us, ms)
}

.sinv_nl <- function(us, vs) {
    .Call('cccp_sinv_nl', PACKAGE = 'cccp', us, vs)
}

.sinv_s <- function(us, vs) {
    .Call('cccp_sinv_s', PACKAGE = 'cccp', us, vs)
}

.sinv_p <- function(us, vs, ms) {
    .Call('cccp_sinv_p', PACKAGE = 'cccp', us, vs, ms)
}

.smsa_nl <- function(us, alphas, inits) {
    .Call('cccp_smsa_nl', PACKAGE = 'cccp', us, alphas, inits)
}

.smsa_s <- function(us, alphas, inits) {
    .Call('cccp_smsa_s', PACKAGE = 'cccp', us, alphas, inits)
}

.smsa1_p <- function(us, alphas, ms) {
    .Call('cccp_smsa1_p', PACKAGE = 'cccp', us, alphas, ms)
}

.smsa2_p <- function(us, alphas, sigmas, lambdas, ms) {
    .Call('cccp_smsa2_p', PACKAGE = 'cccp', us, alphas, sigmas, lambdas, ms)
}

.smss_nl <- function(us) {
    .Call('cccp_smss_nl', PACKAGE = 'cccp', us)
}

.smss_s <- function(us) {
    .Call('cccp_smss_s', PACKAGE = 'cccp', us)
}

.smss_p <- function(us, ms) {
    .Call('cccp_smss_p', PACKAGE = 'cccp', us, ms)
}

.sone_nl <- function(us) {
    .Call('cccp_sone_nl', PACKAGE = 'cccp', us)
}

.sone_s <- function(us) {
    .Call('cccp_sone_s', PACKAGE = 'cccp', us)
}

.sone_p <- function(ms) {
    .Call('cccp_sone_p', PACKAGE = 'cccp', ms)
}

.sprd_nl <- function(us, vs) {
    .Call('cccp_sprd_nl', PACKAGE = 'cccp', us, vs)
}

.sprd_s <- function(us, vs) {
    .Call('cccp_sprd_s', PACKAGE = 'cccp', us, vs)
}

.sprd_p <- function(us, vs, ms) {
    .Call('cccp_sprd_p', PACKAGE = 'cccp', us, vs, ms)
}

.sslb_nl <- function(us, lambdas, invs) {
    .Call('cccp_sslb_nl', PACKAGE = 'cccp', us, lambdas, invs)
}

.sslb_s <- function(us, lambdas, invs) {
    .Call('cccp_sslb_s', PACKAGE = 'cccp', us, lambdas, invs)
}

.sslb_p <- function(us, lambdas, invs, ms) {
    .Call('cccp_sslb_p', PACKAGE = 'cccp', us, lambdas, invs, ms)
}

.ssnt_n <- function(us, Ws, invs) {
    .Call('cccp_ssnt_n', PACKAGE = 'cccp', us, Ws, invs)
}

.ssnt_l <- function(us, Ws, invs) {
    .Call('cccp_ssnt_l', PACKAGE = 'cccp', us, Ws, invs)
}

.ssnt_s <- function(us, Ws, invs) {
    .Call('cccp_ssnt_s', PACKAGE = 'cccp', us, Ws, invs)
}

.ssnt_p <- function(us, Ws, transs, invs) {
    .Call('cccp_ssnt_p', PACKAGE = 'cccp', us, Ws, transs, invs)
}

