# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.sdot_nls <- function(u, v) {
    .Call('cccp_sdot_nls', PACKAGE = 'cccp', u, v)
}

