// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sdot_nls
double sdot_nls(const arma::colvec& u, const arma::colvec& v);
RcppExport SEXP cccp_sdot_nls(SEXP uSEXP, SEXP vSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const arma::colvec& >::type u(uSEXP );
        Rcpp::traits::input_parameter< const arma::colvec& >::type v(vSEXP );
        double __result = sdot_nls(u, v);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
